cargo-features = ["profile-rustflags"]

[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
nc = { version = "0.9.7", default-features = false }

[profile.dev]
panic = "abort"

# [profile.release]
# panic = "abort"

[features]
unit-test = []
